pipelines:
  - name: pipelines_S_PS_I_Google_0001
    steps:
      - name: S_PS_I_Google_0001
        type: PowerShell
        configuration:
          nodePool: awswin_2019
          environmentVariables:
            CLOUDSDK_PYTHON: C:\Python39\python.exe
        execution:
          onExecute:
            - write-output "executing step..."
            - choco install gcloudsdk -y
            - gcloud container images list
